#!/bin/bash
#SBATCH --account=prasanna_1363
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=128G
#SBATCH --time=48:00:00

source /home/ludwika/miniconda3/bin/activate gacg
module load legacy/CentOS7 gcc/11.3.0 git/2.36.1

echo "Starting parallel job script"
/home/ludwika/miniconda3/envs/gacg/bin/python src/main.py --config=qtran --env-config=sensor with seed=5 use_cuda=False t_max=1005000
