#!/bin/bash
#SBATCH --account=prasanna_1363
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=128G
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:1

conda activate gacg
module load legacy/CentOS7 gcc/11.3.0 git/2.36.1

echo "Starting parallel job script"
python3 src/main.py --config=diva_bounded_sigmoid_qmix_DIVA_vscale1_rmax5 --env-config=sensor with seed=8 use_cuda=True
