#!/bin/bash
set -euo pipefail

sbatch runs_baselines/run_1.job
sbatch runs_baselines/run_2.job
sbatch runs_baselines/run_3.job
sbatch runs_baselines/run_4.job
sbatch runs_baselines/run_5.job
sbatch runs_baselines/run_6.job
sbatch runs_baselines/run_7.job
sbatch runs_baselines/run_8.job
sbatch runs_baselines/run_9.job
sbatch runs_baselines/run_10.job
sbatch runs_baselines/run_11.job
sbatch runs_baselines/run_12.job
sbatch runs_baselines/run_13.job
sbatch runs_baselines/run_14.job
sbatch runs_baselines/run_15.job
sbatch runs_baselines/run_16.job
sbatch runs_baselines/run_17.job
sbatch runs_baselines/run_18.job
sbatch runs_baselines/run_19.job
sbatch runs_baselines/run_20.job
sbatch runs_baselines/run_21.job
sbatch runs_baselines/run_22.job
sbatch runs_baselines/run_23.job
sbatch runs_baselines/run_24.job
sbatch runs_baselines/run_25.job
sbatch runs_baselines/run_26.job
sbatch runs_baselines/run_27.job
sbatch runs_baselines/run_28.job
sbatch runs_baselines/run_29.job
sbatch runs_baselines/run_30.job
sbatch runs_baselines/run_31.job
sbatch runs_baselines/run_32.job
sbatch runs_baselines/run_33.job
sbatch runs_baselines/run_34.job
sbatch runs_baselines/run_35.job
sbatch runs_baselines/run_36.job
sbatch runs_baselines/run_37.job
sbatch runs_baselines/run_38.job
sbatch runs_baselines/run_39.job
sbatch runs_baselines/run_40.job
sbatch runs_baselines/run_41.job
sbatch runs_baselines/run_42.job
sbatch runs_baselines/run_43.job
sbatch runs_baselines/run_44.job
sbatch runs_baselines/run_45.job
sbatch runs_baselines/run_46.job
sbatch runs_baselines/run_47.job
sbatch runs_baselines/run_48.job
sbatch runs_baselines/run_49.job
sbatch runs_baselines/run_50.job
sbatch runs_baselines/run_51.job
sbatch runs_baselines/run_52.job
sbatch runs_baselines/run_53.job
sbatch runs_baselines/run_54.job
sbatch runs_baselines/run_55.job
sbatch runs_baselines/run_56.job
sbatch runs_baselines/run_57.job
sbatch runs_baselines/run_58.job
sbatch runs_baselines/run_59.job
sbatch runs_baselines/run_60.job
sbatch runs_baselines/run_61.job
sbatch runs_baselines/run_62.job
sbatch runs_baselines/run_63.job
sbatch runs_baselines/run_64.job
sbatch runs_baselines/run_65.job
sbatch runs_baselines/run_66.job
sbatch runs_baselines/run_67.job
sbatch runs_baselines/run_68.job
sbatch runs_baselines/run_69.job
sbatch runs_baselines/run_70.job
sbatch runs_baselines/run_71.job
sbatch runs_baselines/run_72.job
sbatch runs_baselines/run_73.job
sbatch runs_baselines/run_74.job
sbatch runs_baselines/run_75.job
sbatch runs_baselines/run_76.job
sbatch runs_baselines/run_77.job
sbatch runs_baselines/run_78.job
sbatch runs_baselines/run_79.job
sbatch runs_baselines/run_80.job
sbatch runs_baselines/run_81.job
sbatch runs_baselines/run_82.job
sbatch runs_baselines/run_83.job
sbatch runs_baselines/run_84.job
sbatch runs_baselines/run_85.job
sbatch runs_baselines/run_86.job
sbatch runs_baselines/run_87.job
sbatch runs_baselines/run_88.job
sbatch runs_baselines/run_89.job
sbatch runs_baselines/run_90.job
sbatch runs_baselines/run_91.job
sbatch runs_baselines/run_92.job
sbatch runs_baselines/run_93.job
sbatch runs_baselines/run_94.job
sbatch runs_baselines/run_95.job
sbatch runs_baselines/run_96.job
